DROP TABLE IF EXISTS `Tokens`;
DROP TABLE IF EXISTS `Menu`;
DROP TABLE IF EXISTS `Event_prices`;
DROP TABLE IF EXISTS `Restaurants`;
DROP TABLE IF EXISTS `Admins`;
DROP TABLE IF EXISTS `Super_admins`;
